Generating file section
frenzymadness/specfile_generator pull request #5
Opened 2019-09-27 14:31 UTC by PatrikKopkan

2019-09-30 10:01 UTC, frenzymadness requested changes
Looks good to me. Just a few nitpicks. Let me know if you want to discuss them further.

2019-09-30 10:01 UTC, frenzymadness commented on gen_spec.py
> +    main()
Please, keep the newline at the end of the file.

2019-09-30 10:01 UTC, frenzymadness commented on template.spec
> -
Why not keep an empty line between the %install and %check sections?

2019-09-30 10:01 UTC, frenzymadness commented on gen_spec.py
> +    tempvenv = TemporaryDirectory()
`tempdir` would be a better name, I think because it contains the path to the directory and not to the virtual environment.

2019-09-30 10:01 UTC, frenzymadness commented on template.spec
> +URL:            {{ pypi['info']['Home-page'] or pypi['info']['project_url']) }}
jinja2.exceptions.TemplateSyntaxError: unexpected ')'

2019-09-30 10:01 UTC, frenzymadness commented on gen_spec.py
> +    '%{python3_sitelib}': '',
These lines should be indented.

2019-09-30 10:01 UTC, frenzymadness commented on gen_spec.py
> +    for key, value in macros.items():
`value` is unused, why not just `for macro in macros:`?

2019-09-30 10:01 UTC, frenzymadness commented on gen_spec.py
> +    for file in files:
This is not effective because the two for loops create a matrix `<n files> × <n macros>` but the `replace` actually does something just once for each file. Just an idea: we can merge all files into one string, do the replace for every macro and then split the files back to a list of files.

2019-09-30 10:01 UTC, frenzymadness commented on gen_spec.py
> +        if line.startswith('Location:'):
Please add a comment here what the "Location" means and what is the result of its processing.

2019-10-10 16:28 UTC, PatrikKopkan commented
tryied to generate pytest. built and upgrades fine.

2019-10-11 11:11 UTC, frenzymadness approved these changes
Good! Works for me with pytest, tldr and hatch packages

2019-10-11 11:11 UTC, merged